// Application-wide constants for the LLMOps Chat frontend.
// All AI responses are generated by the local RAG pipeline via app-gateway.

export const DEFAULT_SYSTEM_PROMPT =
  process.env.DEFAULT_SYSTEM_PROMPT ||
  'You are a helpful AI assistant powered by a local RAG pipeline. Answer questions clearly and accurately based on the retrieved context.';
