# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\tmlservice\" \n\x0f\x43lassifyRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x85\x01\n\x10\x43lassifyResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x16\n\x0ereasoning_type\x18\x02 \x01(\t\x12\x10\n\x08\x65ntities\x18\x03 \x03(\t\x12\r\n\x05scope\x18\x04 \x01(\t\x12\x11\n\tambiguity\x18\x05 \x01(\t\x12\x15\n\rsub_questions\x18\x06 \x03(\t\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"1\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\" \n\x0eRerankResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x32\xcb\x01\n\tMlService\x12\x43\n\x08\x43lassify\x12\x1a.mlservice.ClassifyRequest\x1a\x1b.mlservice.ClassifyResponse\x12:\n\x05\x45mbed\x12\x17.mlservice.EmbedRequest\x1a\x18.mlservice.EmbedResponse\x12=\n\x06Rerank\x12\x18.mlservice.RerankRequest\x1a\x19.mlservice.RerankResponseB$\n\x10\x63om.llmops.protoB\x0eMlServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.llmops.protoB\016MlServiceProtoP\001'
  _globals['_CLASSIFYREQUEST']._serialized_start=31
  _globals['_CLASSIFYREQUEST']._serialized_end=63
  _globals['_CLASSIFYRESPONSE']._serialized_start=66
  _globals['_CLASSIFYRESPONSE']._serialized_end=199
  _globals['_EMBEDREQUEST']._serialized_start=201
  _globals['_EMBEDREQUEST']._serialized_end=229
  _globals['_EMBEDRESPONSE']._serialized_start=231
  _globals['_EMBEDRESPONSE']._serialized_end=265
  _globals['_RERANKREQUEST']._serialized_start=267
  _globals['_RERANKREQUEST']._serialized_end=316
  _globals['_RERANKRESPONSE']._serialized_start=318
  _globals['_RERANKRESPONSE']._serialized_end=350
  _globals['_MLSERVICE']._serialized_start=353
  _globals['_MLSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
