class RetrievalQualityGate:
    """
    Evaluates retrieval quality and decides whether to retry.
    Uses reranker scores — no additional LLM call needed.
    """
    
    # Minimum average reranker score for top-3 results.
    # Scores from CrossEncoder are typically logits or probabilities.
    # We want a conservative threshold so we don't trigger retries constantly,
    # but still catch cases where the results are completely irrelevant.
    QUALITY_THRESHOLDS = {
        "commonsense": 0.1,    # Simple questions need moderate relevance
        "adaptive": 0.05,      # Multi-part can tolerate lower per-doc relevance  
        "strategic": 0.02,     # Comparative queries have broader context needs
    }
    
    def evaluate(self, reranked_results: list, reasoning_type: str):
        """
        Returns a tuple: (passed: bool, avg_score: float, threshold: float)
        """
        if not reranked_results:
            return False, 0.0, self.QUALITY_THRESHOLDS.get(reasoning_type, 0.1)
        
        top_scores = [r["final_score"] for r in reranked_results[:3]]
        avg_score = sum(top_scores) / len(top_scores)
        threshold = self.QUALITY_THRESHOLDS.get(reasoning_type, 0.1)
        
        passed = avg_score >= threshold
        return passed, avg_score, threshold
    
    def refine_query(self, original_query: str, classification: dict) -> str:
        """Generate a refined search query by adding domain context or using sub-questions."""
        sub_questions = classification.get("sub_questions", [])
        if sub_questions and len(sub_questions) > 0 and sub_questions[0] != original_query:
            # Use the first sub-question generated by the classifier, as it is often more concrete
            return sub_questions[0]
        
        # Heuristic refinement based on intent
        intent = classification.get("intent", "factual")
        refined = original_query.strip()
        
        # If it doesn't already specify code-level details and it's programming-related, append helpful context
        if intent == "procedural" and not any(w in refined.lower() for w in ["code", "example", "how to"]):
            refined = f"{refined} code example implementation"
        elif intent == "debugging" and not any(w in refined.lower() for w in ["error", "exception", "fix", "solve"]):
            refined = f"{refined} error exception fix solution"
            
        return refined
