---
- name: Deploy Enterprise LLMOps Platform to Minikube
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    k8s_namespace: "llmops-platform"
    docker_registry: "poojan"
    image_tag: "latest"
    redis_password: "SuperSecureRedisPassword123"
    vault_root_token: "root-token"
    vault_secret_path: "llmops-platform"
    ollama_model: "gemma2:2b"
    build_dir: "{{ playbook_dir }}/build"

  roles:
    - k8s_deploy
